version: '4'
services:
  mongodb:
    image: mongo:4.4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db

#do research on these configs!!!!!!!




#    product-service:
#        image: mainagerald/product-service:latest
#        environment:
#            - SPRING_PROFILES_ACTIVE=docker
#        depends_on:
#            - zipkin
#            - broker
#            - discovery-server
#            - api-gateway
