version: '4'
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MY_SQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql